### ISSUE TITLE
Update design and images on landing page

### ISSUE THREAD

**Issue by griebelr** [TridentMarketing/Adventure-Pass#62]
- [ ] Replace header image with a slideshow video to be created
- [x] Add a section with a map that shows resort locations plus partner resort locations
- [ ] Header copy of map section: **Looking for Even More Adventure?**
- [ ] Sub head copy of map section: Get access to hundreds more campgrounds and vacation rentals nationwide with a membership to our exclusive Partner Resorts. **Member rates for only $129 per year!**
- [ ] Call to action in map section: Call today to learn more or request more information 
        [Call 855-481-6542] OR [Request More Info] 
         >> Request More Info << opens a lead form page
- [x] Replace Reviews section with Google reviews from tra site
- [x] Add Events section from tra site
- [x] Add Insta and FB links and previews

**Comment by aliirz** [comment]
@griebelr to provide map

**Comment by aliirz** [comment]
the events in tra website are managed via a Wordpress plugin. fastest course of action  will be just adding a few events statically. we cant build a event mgmt system seperately

**Comment by jawariawaseem** [comment]
@griebelr can you please provide the map?

**Comment by griebelr** [comment]
@jawariawaseem  I requested it last week but still have not received it from marketing. Let me ask for it again.

**Comment by griebelr** [comment]
This is all I was able to get![Image](https://github.com/user-attachments/assets/5a2bce81-3537-4894-a7db-89d5d67ebbe2)

**Comment by griebelr** [comment]
@jawariawaseem I added a new item to the main requirements -- to replace the header image with the video that's running on the travelresorts.com home page

**Comment by AmnaDM** [comment]
Awaiting video and content from @griebelr

**Comment by griebelr** [comment]
CHANGE REQUEST:

- [x] Move the Camp All Year Partner Resorts map up on the page

![Image](https://github.com/user-attachments/assets/b787f49f-c93b-4a8a-83f0-aca00739f4af)

- [x] Add header text above map as shown below
- [x] Add call to action buttons below map as shown below

![Image](https://github.com/user-attachments/assets/08502d09-a44f-4961-830e-0c09cb96bafe)

- [x] Call for More Info is call to click
- [x] Add it When You Buy opens purchase page (same as the Start Camping Today and Join Now buttons)

**Comment by griebelr** [comment]
CHANGE REQUEST:

- [x] Update Header content as shown below

![Image](https://github.com/user-attachments/assets/1f9f7ee6-f90c-4a19-a09e-2dab484e6c18)

**Comment by griebelr** [comment]
CHANGE REQUEST:

- [x] Remove static Testimonials section and link 'Reviews' to Google Review section

![Image](https://github.com/user-attachments/assets/1a98f872-e7a2-43c6-9464-d445fcbfe9d2)

**Comment by griebelr** [comment]
CHANGE REQUEST:

- [ ] Update content above the fold as shown below, also attached in PPT slide

![Image](https://github.com/user-attachments/assets/046f76d1-245c-49e1-95b4-49789cc54528)

[Updated AP Landing Page Header.pptx](https://github.com/user-attachments/files/17192652/Updated.AP.Landing.Page.Header.pptx)

**Comment by griebelr** [comment]
- [x] Change header hero image - will provide a few to choose
- [x] Move logo to left corner and make menu across top
       Why Us?    Reviews    Locations    Our Guarantee      Call Today 855-481-6542
- [x] Remove 'Already a Pass Holder' from the menu
- [x] Only include this text in hero section
                   Your Adventure Awaits!
         Camp All Year with No Nightly Fees
Only $599 for an Entire Year of Endless Camping

             Buy TODAY and get $50 OFF!

- [ ] Add a timer with an end date of December 1, 2024.
- [x] Add new section above Regions for offer text - will provide some background images.
        With the Adventure Pass you can camp all year round for one low price!
         [Insert bulleted list from content above]

Look at thousandtrails.com for example and reference of layout and design.
Look at promotional PDF design for email blast attached for reference.

![Image](https://github.com/user-attachments/assets/804e9eee-0425-4171-957c-4d9c7fde1e24)
![Image](https://github.com/user-attachments/assets/c0dd2158-a1eb-4921-a54d-3503ac31b43b)
[TravelResorts-HoneyCampaign1024v8.pdf](https://github.com/user-attachments/files/17298764/TravelResorts-HoneyCampaign1024v8.pdf)

**Comment by griebelr** [comment]
Some additional photos to play around with

![Image](https://github.com/user-attachments/assets/9a02704a-e18b-4048-b92c-aefbb7893fe8)
![Image](https://github.com/user-attachments/assets/6c584594-828e-490c-aab4-ee4f303c8ce7)
![Image](https://github.com/user-attachments/assets/b95b6077-2d91-4e15-942e-01bf938172cf)
![Image](https://github.com/user-attachments/assets/ec7377f1-5b53-46ce-8671-d829f920c6c2)
![Image](https://github.com/user-attachments/assets/861576ff-8e0c-4894-80b3-f14b4bb1f2f3)

**Comment by griebelr** [comment]
- [x] Flip the menu so the Adventure Pass "logo" and the menu options are at the top and the phone number is below
- [x] Can we find a more interesting font for the Adventure Pass TM "logo" ? It's very boring
- [x] Remove the Speak to a Specialist label
- [x] Add 'For More Info Call' to the phone number button
![Image](https://github.com/user-attachments/assets/ee9b2a9e-2e95-4e10-944f-bf86a89cfeb9)

- [x] Let's play with some better fonts. The sans serif on 'Camp All Year with No Nightly Fees' is very boring.
- [x] Add to 'Camp All Year...' full text says "Camp All Year with No Nightly Fees and No Commitment"

**Comment by griebelr** [comment]
- [x] Replace the bullets in this section with this copy
- Access to 11 premier RV Parks throughout the Northeast, Southeast, and Midwest
- Full hookup RV sites, tent sites, and cabins available
- Pet friendly
- Loads of amenities and local attractions
- Family-friendly communities
- Lifelong memories

![Image](https://github.com/user-attachments/assets/ce80dffd-68c8-4221-b658-96bc06d23ad3)

**Comment by griebelr** [comment]
Here are a few more photos for this section. See how it ends with blank space. Can we add enough photos and fix the scroll so it does not do this. Mix the landscape photos with the people images.

![Image](https://github.com/user-attachments/assets/76a57b3e-2bf9-4978-bc17-447076b20148)
![Image](https://github.com/user-attachments/assets/02fb6289-4b15-4917-a8a2-175e86598484)
![Image](https://github.com/user-attachments/assets/5e6964a6-abf1-4f55-a7fe-d836952e6467)
![Image](https://github.com/user-attachments/assets/ef29563c-b33a-40c2-b11a-101e09d74e47)
![Image](https://github.com/user-attachments/assets/17e5c127-f83c-477a-a556-5c5c3623e8ab)
![Image](https://github.com/user-attachments/assets/2be0fd0a-fd4c-40ec-b00e-99f246cfe8c6)
![Image](https://github.com/user-attachments/assets/a4bba1f4-cb5f-4de8-9130-23df11acc4ee)

**Comment by griebelr** [comment]
- [x] Increase font size and change copy as shown below.
![Image](https://github.com/user-attachments/assets/b304cd26-fee9-466b-9c4a-699e8d170e75)

**Comment by griebelr** [comment]
- [x] Add a count down timer to the hero section with additional copy as shown below
![Image](https://github.com/user-attachments/assets/a0c0683b-0a2b-4299-bd4d-e8d0387d2d99)

**Comment by griebelr** [comment]
- [x] Increase font size of primary tag lines in hero section
- [x] Increase font size of text below "Join in on the fun for one low price!" 
- [x] Increase font size of text below "Looking For Even More Adventure?" above map image
- [x] Remove image in footer and replace with AP logo image
- [x] Replace Twitter logo with X logo
@SHassan1593 ^
